name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features & Improvements'
    labels:
      - 'enhancement'
      - 'improvement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '🔧 Other Changes'
    labels: []
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
    collapse-after: 3
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&#@'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
